# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"
  config.vm.box = "geerlingguy/centos7"
  config.vm.provider "virtualbox" do |v|
   v.memory = 1024
   v.cpus = 1
  end

  config.vm.define "node" do |machine|
   config.vm.boot_timeout = 5000
   config.vm.network "private_network", ip: "192.168.1.10"

   machine.vm.provision :ansible_local do |ansible|
     ansible.playbook       = "main.yml"
     ansible.verbose        = true
     ansible.install        = true
     ansible.limit          = "all"
     ansible.inventory_path = "hosts"
   end
  end   

end

 
